src/main/java/beans/CadastroPessoasBean.java
package beans;

import java.io.Serializable;
import java.util.*;
import java.util.logging.Logger;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.faces.event.AjaxBehaviorEvent;
import javax.faces.event.ComponentSystemEvent;
import javax.faces.event.ValueChangeEvent;
import javax.inject.Named;

import jdk.nashorn.internal.ir.CallNode;
import lombok.Getter;
import lombok.Setter;
import modelo.Pessoa;
import modelo.PessoaFisica;
import modelo.PessoaJuridica;
import modelo.Sexo;

@Getter
@Setter
@ApplicationScoped
@ManagedBean
public class CadastroPessoasBean implements Serializable {
  private static final long serialVersionUID = 1L;
  private Pessoa pessoaSelecionada;
  private List<Pessoa> lista = new ArrayList<>();
  private String tipoNovaPessoa;
  private Locale locale;
  private String codigoGet;

  public CadastroPessoasBean() {
    for (int x = 0; x < 10; x++) {
      Pessoa p = (x % 2 == 0) ? new PessoaFisica() : new PessoaJuridica();
      p.setCodigo(x + 1L);
      p.setNome(String.format("Pessoa %02d", x));
      p.setTelefone(String.format("9999-88%02d", x));
      p.setEmail(String.format("fulano-%02d@email.com", x));
      lista.add(p);
      locale = FacesContext.getCurrentInstance().getExternalContext().getRequestLocale();
    }
  }

  public Sexo[] getSexos() {
    return Sexo.values();
  }

  public void criar() {
    FacesContext context = FacesContext.getCurrentInstance();
    if (tipoNovaPessoa == null) {
      context.addMessage(
          null, new FacesMessage(FacesMessage.SEVERITY_WARN, "Você deve especificar o tipo.", ""));
      return;
    } else if (tipoNovaPessoa.equals("PF")) {
      pessoaSelecionada = new PessoaFisica();
    } else if (tipoNovaPessoa.equals("PJ")) {
      pessoaSelecionada = new PessoaJuridica();
    }
    context.addMessage(
        null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Pessoa criada com sucesso.", ""));
  }

  public String salvar() {
    if (!lista.contains(this.pessoaSelecionada)) lista.add(this.pessoaSelecionada);
    FacesContext contexto = FacesContext.getCurrentInstance(); /*
    contexto.addMessage(
        null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Edição realizada com sucesso.", ""));*/
    contexto
        .getExternalContext()
        .getFlash()
        .put(
            "mensagem",
            new FacesMessage(FacesMessage.SEVERITY_INFO, "Edição realizada com sucesso.", ""));
    return "sucesso";
  }

  public void excluir() {
    lista.remove(this.pessoaSelecionada);
    pessoaSelecionada = null;
    String mensagem = ResourceBundle.getBundle("bundles.messages", locale).getString("excluida");
    FacesContext.getCurrentInstance()
        .addMessage(
            null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Pessoa excluída com sucesso.", ""));
  }

  public String cancelar() {
    pessoaSelecionada = null;
    tipoNovaPessoa = null;
    return "inicio";
  }

  public void setCodigoGet(String codigoGet) {
    this.codigoGet = codigoGet;
    Logger.getLogger(Logger.GLOBAL_LOGGER_NAME).info("SETOU O CÓDIGO GET PARA " + codigoGet);
  }

  public boolean isPessoaFisicaSelecionada() {
    return pessoaSelecionada instanceof PessoaFisica;
  }

  public boolean isPessoaJuridicaSelecionada() {
    return pessoaSelecionada instanceof PessoaJuridica;
  }

  public void ouvinteAjax(AjaxBehaviorEvent event) {
    Logger.getLogger(Logger.GLOBAL_LOGGER_NAME).info("AJAX " + event.getPhaseId());
  }

  public void ouvinteAjax(ValueChangeEvent event) {
    Logger.getLogger(Logger.GLOBAL_LOGGER_NAME).info("AJAX value change " + event.getPhaseId());
  }

  public void viewListener(ComponentSystemEvent event) {
    if (codigoGet != null && !codigoGet.isEmpty()) {
      pessoaSelecionada = lista.get(Integer.parseInt(getCodigoGet()) - 1);
      Logger.getLogger(Logger.GLOBAL_LOGGER_NAME)
          .info("viewListener chamado. Pessoa selecionada: " + getPessoaSelecionada().getNome());
    }
  }
}

src/main/java/beans/CadastroQuartosBean.java
package beans;

import lombok.Getter;
import lombok.Setter;
import lombok.extern.java.Log;
import modelo.Quarto;
import modelo.TipoDeQuarto;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UISelectItems;
import javax.faces.component.html.HtmlSelectOneMenu;
import javax.faces.context.FacesContext;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

@ManagedBean
@SessionScoped
@Getter
@Setter
public class CadastroQuartosBean {
  private Quarto quartoAtual;
  private List<Quarto> lista;
  // CDI não é compatível com Backing Beans
  private HtmlSelectOneMenu selectTipos;

  public CadastroQuartosBean() {
    this.quartoAtual = new Quarto();
    this.lista = new ArrayList<>();
    this.selectTipos = new HtmlSelectOneMenu();
    UISelectItems itens = new UISelectItems();
    itens.getAttributes().put("value", TipoDeQuarto.values());
    selectTipos.getChildren().add(itens);
  }

  @PostConstruct
  public void construir() {
    Logger.getLogger(Logger.GLOBAL_LOGGER_NAME).info("Cadastro de quartos construído!");
  }

  @PreDestroy
  public void destruir() {
    Logger.getLogger(Logger.GLOBAL_LOGGER_NAME).info("Cadastro de quartos destruído!");
  }

  public String salvar() {
    if (!lista.contains(this.quartoAtual)) {
      lista.add(this.quartoAtual);
      this.quartoAtual = new Quarto();
    }
    this.quartoAtual = new Quarto();
    FacesContext contexto = FacesContext.getCurrentInstance();
    contexto.addMessage(
        null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Edição realizada com sucesso.", ""));
    return "sucesso";
  }

  public void excluir() {
    lista.remove(quartoAtual);
    quartoAtual = new Quarto();
    FacesContext.getCurrentInstance()
        .addMessage(
            null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Quarto excluído com sucesso.", ""));
  }

  public String cancelar() {
    this.quartoAtual = new Quarto();
    return "inicio";
  }
}

src/main/java/beans/GeralBean.java
package beans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.faces.event.ValueChangeEvent;

@ManagedBean
@SessionScoped
public class GeralBean implements Serializable {
  private Locale locale;
  private List<Locale> localesDisponiveis = new ArrayList<>();

  public GeralBean() {
    Iterator<Locale> it = FacesContext.getCurrentInstance().getApplication().getSupportedLocales();
    while (it.hasNext()) {
      localesDisponiveis.add(it.next());
    }
    locale = FacesContext.getCurrentInstance().getViewRoot().getLocale();
  }

  public Locale getLocale() {
    return locale;
  }

  public void setLocale(Locale locale) {
    this.locale = locale;
  }

  public List<Locale> getLocalesDisponiveis() {
    return localesDisponiveis;
  }

  public void setLocalesDisponiveis(List<Locale> localesDisponiveis) {
    this.localesDisponiveis = localesDisponiveis;
  }

  public void atualizarLocale(ValueChangeEvent event) {
    FacesContext.getCurrentInstance().getViewRoot().setLocale((Locale) event.getNewValue());
  }

  public void atualizarLocale(ActionEvent event) {
    Locale l = (Locale) event.getComponent().getAttributes().get("locale");
    if (l != null) locale = l;
    FacesContext.getCurrentInstance().getViewRoot().setLocale(this.locale);
  }

  public void atualizarLocale() {
    System.out.println("locale atualizado.");
  }
}

src/main/java/beans/MeuPrimeiroBean.java
package beans;

import java.io.Serializable;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@SessionScoped
@Named
public class MeuPrimeiroBean implements Serializable {
  private static final long serialVersionUID = 1L;
  private String ola = "<strong>Olá amigos.</strong>";
  private boolean exibir = true;
}

src/main/java/beans/PrimeFacesBean.java
package beans;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.el.MethodExpression;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import org.primefaces.event.SelectEvent;

@ManagedBean
@SessionScoped
public class PrimeFacesBean {
  private Date data;

  public Date getData() {
    return data;
  }

  public void setData(Date data) {
    this.data = data;
  }

  public void definirData(SelectEvent<Date> event) {
    SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    setData(event.getObject());
    FacesContext.getCurrentInstance()
        .addMessage(null, new FacesMessage("Data alterada", "A data agora é " + getData()));
  }
}

src/main/java/com/nallon/udemyjsfreservashotel/HelloServlet.java
package com.nallon.udemyjsfreservashotel;

import java.io.*;
import javax.servlet.http.*;
import javax.servlet.annotation.*;

@WebServlet(name = "helloServlet", value = "/hello-servlet")
public class HelloServlet extends HttpServlet {

  private String message;

  public void init() {
    message = "Hello World!";
  }

  public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
    response.setContentType("text/html");

    // Hello
    PrintWriter out = response.getWriter();
    out.println("<html><body>");
    out.println("<h1>" + message + "</h1>");
    out.println("</body></html>");
  }

  public void destroy() {
  }
}

src/main/webapp/cadastropessoas.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:esp="http://www.especiliza.com.br/facelets/taglibs"
      xmlns:espc="http://xmlns.jcp.org/jsf/composite/componentes"
>
<ui:composition template="estrutura.xhtml">
    <script type="text/javascript">
        function functionError() {
        }

        function functionEvent(data) {
            /*var mensagem = "";
            for (var i in data) {
              mensagem += i + ": " + data[i] + "\n";
            }
            alert(mensagem);*/
        }
    </script>
    <ui:define name="direita">
        <h:messages infoClass="info" errorClass="erro" warnClass="warn" fatalClass="fatal"/>
        #{flash.mensagem.summary}
    </ui:define>
    <f:metadata>
        <f:viewParam name="codigo" value="#{cadastroPessoasBean.codigoGet}"/>
        <f:event listener="#{cadastroPessoasBean.viewListener}" type="preRenderView"/>
    </f:metadata>
    <h1>Cadastro de pessoas:</h1>
    <h:outputFormat value="#{mens.editar}"
                    rendered="#{not empty cadastroPessoasBean.pessoaSelecionada.nome}">
        <f:param value="#{cadastroPessoasBean.pessoaSelecionada.nome}"/>
    </h:outputFormat>
    <h:form>
        <h:panelGrid columns="3">
            ${mens.escolha}
            <h:selectOneMenu value="#{geralBean.locale}">
                <f:selectItems value="#{geralBean.localesDisponiveis}"/>
                <f:converter converterId="conversorLocale"/>
            </h:selectOneMenu>
            <h:commandButton value="Ok" action="#{geralBean.atualizarLocale}"/>
        </h:panelGrid>
    </h:form>
    <h:form rendered="#{empty cadastroPessoasBean.pessoaSelecionada}">
        <h:panelGrid id="gridTipoPessoa" columns="2">
            <f:facet name="header">Tipo pessoa:</f:facet>
            <h:selectOneRadio value="#{cadastroPessoasBean.tipoNovaPessoa}">
                <f:selectItem itemLabel="Pessoa física" itemValue="PF"/>
                <f:selectItem itemLabel="Pessoa jurídica" itemValue="PJ"/>
            </h:selectOneRadio>
            <h:commandButton value="Criar nova" action="#{cadastroPessoasBean.criar}"/>
        </h:panelGrid>
    </h:form>
    <h:form rendered="#{not empty cadastroPessoasBean.pessoaSelecionada}">
        <h:panelGrid columns="3">
            <f:facet name="header">Dados gerais:</f:facet>

            <h:outputLabel for="nome" value="Nome:"/>
            <h:inputText id="nome"
                         valueChangeListener="#{cadastroPessoasBean.ouvinteAjax}"
                         value="#{cadastroPessoasBean.pessoaSelecionada.nome}">
                <f:ajax event="keyup"
                        listener="#{cadastroPessoasBean.ouvinteAjax}"/>
            </h:inputText>
            <h:message styleClass="erro" for="nome"/>

            <h:outputLabel for="email" value="E-mail:"/>
            <h:inputText id="email" value="#{cadastroPessoasBean.pessoaSelecionada.email}"
                         validatorMessage="E-mail inválido.">
                <f:validateRegex pattern=".+@.+"/>
                <f:ajax render="mensEmail :formTabela:tabela"
                        execute="@this"
                        onerror="functionError"
                        onevent="functionEvent"/>
            </h:inputText>
            <h:message id="mensEmail" styleClass="erro" for="email"/>
            <h:outputLabel for="telefone" value="Telefone:"/>
            <h:inputText id="telefone"
                         value="#{cadastroPessoasBean.pessoaSelecionada.telefone}"/>
            <h:message styleClass="erro" for="telefone"/>
        </h:panelGrid>
        <h:panelGrid columns="3" id="gridPessoaFisica"
                     rendered="#{cadastroPessoasBean.pessoaFisicaSelecionada}">
            <f:facet name="header">Dados pessoa física:</f:facet>
            <h:outputLabel value="RG" for="rg"/>
            <h:inputText id="rg" value="#{cadastroPessoasBean.pessoaSelecionada.rg}"/>
            <h:message for="rg" styleClass="erro"/>
            <h:outputLabel value="CPF" for="cpf"/>
            <h:inputText id="cpf" value="#{cadastroPessoasBean.pessoaSelecionada.cpf}"
                         validatorMessage="CPF inválido.">
                <f:validateRegex pattern="\d{3}\.\d{3}\.\d{3}\-\d{2}"/>
                <f:validator validatorId="validadorDeCPF"/>
            </h:inputText>
            <h:message styleClass="erro" for="cpf"/>
            <h:outputLabel value="Data de nascimento" for="dataNascimento"/>
            <h:inputText id="dataNascimento"
                         value="#{cadastroPessoasBean.pessoaSelecionada.dataNascimento}"
                         converterMessage="Insira a data no formato dd/MM/yyyy">
                <f:convertDateTime pattern="dd/MM/yyyy" type="date"/>
            </h:inputText>
            <h:message styleClass="erro" for="dataNascimento"/>
            <h:outputLabel value="Sexo" for="sexo"/>
            <h:selectOneRadio id="sexo"
                              value="#{cadastroPessoasBean.pessoaSelecionada.sexo}">
                <f:selectItems value="#{cadastroPessoasBean.sexos}" var="s"
                               itemLabel="#{s.nome}"/>
            </h:selectOneRadio>
            <h:message styleClass="erro" for="sexo"/>
        </h:panelGrid>
        <h:panelGrid id="gridPessoaJuridica"
                     rendered="#{cadastroPessoasBean.pessoaJuridicaSelecionada}"
                     columns="3">
            <f:facet name="header">Dados pessoa jurídica:</f:facet>
            <h:outputLabel value="CNPJ" for="cnpj"/>
            <h:inputText id="cnpj" value="#{cadastroPessoasBean.pessoaSelecionada.cnpj}"
                         validatorMessage="CNPJ inválido.">
                <f:validateRegex pattern="\d{2}(\.\d{3}){2}/\d{4}-\d{2}"/>
            </h:inputText>
            <h:message styleClass="erro" for="cnpj"/>
            <h:outputLabel value="Razão social" for="razaoSocial"/>
            <h:inputText id="razaoSocial"
                         value="#{cadastroPessoasBean.pessoaSelecionada.razaoSocial}"/>
            <h:message styleClass="erro" for="razaoSocial"/>
            <h:outputLabel value="Inscrição estadual" for="inscricaoEstadual"/>
            <h:inputText id="inscricaoEstadual"
                         value="#{cadastroPessoasBean.pessoaSelecionada.inscricaoEstadual}"/>
            <h:message styleClass="erro" for="inscricaoEstadual"/>
            <h:outputLabel value="Inscrição municipal" for="inscricaoMunicipal"/>
            <h:inputText id="inscricaoMunicipal"
                         value="#{cadastroPessoasBean.pessoaSelecionada.inscricaoMunicipal}"/>
            <h:message styleClass="erro" for="inscricaoMunicipal"/>
        </h:panelGrid>
        <h:commandButton action="#{cadastroPessoasBean.salvar}"
                         image="#{resource['img:salvar.png']}"/>
        <h:commandButton immediate="true"
                         action="#{cadastroPessoasBean.cancelar}"
                         image="#{resource['img:cancelar.png']}"/>
    </h:form>
    <h:form id="formTabela">
        <h2>Lista de pessoas cadastradas:</h2>
        <h:dataTable id="tabela" value="#{cadastroPessoasBean.lista}" var="p">
            <esp:coluna nome="Nome" valor="#{p.nome}" escapar="true"/>
            <esp:coluna nome="E-mail" valor="#{p.email}" escapar="true"/>
            <esp:coluna nome="Telefone" valor="#{p.telefone}" escapar="true"/>
            <h:column>
                <f:facet name="header">Ações:</f:facet>
                <espc:editarExcluir alvo="#{cadastroPessoasBean.pessoaSelecionada}"
                                    excluirListener="#{cadastroPessoasBean.excluir}"
                                    objeto="#{p}"
                />
            </h:column>
        </h:dataTable>
    </h:form>
</ui:composition>
</html>

src/main/webapp/cadastroquartos.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:esp="http://www.especiliza.com.br/facelets/taglibs"
      xmlns:espc="http://xmlns.jcp.org/jsf/composite/componentes"
>
<ui:composition template="estrutura.xhtml">
    <ui:define name="direita">
        <h:messages infoClass="info" errorClass="erro" warnClass="warn" fatalClass="fatal"/>
        #{flash.mensagem.summary}
    </ui:define>
    <h1>Cadastro de quartos:</h1>
    <h:form id="formDados">
        <h:panelGrid columns="3">
            <f:facet name="header">Dados do quarto:</f:facet>
            <h:outputLabel for="numero" value="Número:"/>
            <h:inputText id="numero" value="#{cadastroQuartosBean.quartoAtual.numero}"/>
            <h:message for="numero"/>
            <h:outputLabel for="tipo" value="Tipo:"/>
            <h:selectOneMenu id="tipo" value="#{cadastroQuartosBean.quartoAtual.tipo}"
                             binding="#{cadastroQuartosBean.selectTipos}"/>
        </h:panelGrid>
        <h:commandButton action="#{cadastroQuartosBean.salvar}"
                         image="#{resource['img:salvar.png']}"/>
        <h:commandButton immediate="true"
                         action="#{cadastroQuartosBean.cancelar}"
                         image="#{resource['img:cancelar.png']}"/>
    </h:form>
    <h:form id="formTabela">
        <h2>Lista de quartos cadastrados:</h2>
        <h:dataTable id="tabela" value="#{cadastroQuartosBean.lista}" var="q" rowClasses="linha1, linha 2">
            <esp:coluna nome="Número:" valor="#{q.numero}" escapar="true" informar="false"/>
            <esp:coluna nome="Tipo:" valor="#{q.tipo}" escapar="true" informar="false"/>
            <h:column>
                <f:facet name="header">Ações</f:facet>
                <espc:editarExcluir alvo="#{cadastroQuartosBean.quartoAtual}"
                                    excluirListener="#{cadastroQuartosBean.excluir}"/>
            </h:column>
        </h:dataTable>
    </h:form>
</ui:composition>
</html>

src/main/webapp/estrutura.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xml:lang="en" lang="en">

<h:head>
    <title>#{titulo}</title>
    <!--<ui:insert name="titulo">Um título que vai ser modificado pela página.</ui:insert>-->
    <!--<link rel="stylesheet" href="css/style.css"/> -->
    <h:outputStylesheet library="css" name="styles.css"/>
    <!-- <h:outputStylesheet value="#{resource['css:styles.css']}"/>-->
</h:head>
<h:body>
    <div id="topo">
        <h:graphicImage name="especializa.jpg" library="img"/>
        <h:form>
            <ui:repeat var="l" value="#{geralBean.localesDisponiveis}">
                <h:commandButton image="bandeiras/#{l}.gif"
                                 actionListener="#{geralBean.atualizarLocale}">
                    <f:attribute name="locale" value="#{l}"/>
                </h:commandButton>
            </ui:repeat>
        </h:form>
    </div>
    <div id="conteudo">
        <div id="esquerda">
            <ui:include src="menu.xhtml"/>
        </div>
        <div id="direita">
            <ui:insert name="direita">O que vem do lado direito.</ui:insert>
        </div>
        <div id="centro">
            <ui:insert>O que vem no centro.</ui:insert>
        </div>
    </div>
    <div id="rodape">
        <strong>Specializa treinamentos</strong><br/>
        +55 55 5555-5555
    </div>
</h:body>
</html>

src/main/webapp/index.jsp
<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<!DOCTYPE html>
<html>
<head>
    <title>JSP - Hello World</title>
</head>
<body>
<h1><%= "Hello World!" %>
</h1>
<br/>
<a href="hello-servlet">Hello Servlet</a>
</body>
</html>

src/main/webapp/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xml:lang="en" lang="en">
<ul>
    <li><h:link outcome="inicio" value="Primeiro"/></li>
    <li><h:link outcome="cadastropessoas.jsf" value="Cadastro de pessoas"/></li>
    <li><h:link outcome="cadastroquartos.jsf" value="Cadastro de quartos"/></li>
    <li><h:link outcome="primefaces.jsf" value="Exemplo de PrimeFaces"/></li>
</ul>
</html>

src/main/webapp/primefaces.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:esp="http://www.especiliza.com.br/facelets/taglibs"
      xmlns:espc="http://xmlns.jcp.org/jsf/composite/componentes"
      xmlns:p="http://primefaces.org/ui"
>
<ui:composition template="estrutura.xhtml">
    <ui:param name="titulo" value="Exemplos PrimeFaces"/>
    <ui:define name="direita">
        <p:growl showDetail="true" id="mensagens"/>
    </ui:define>
    <h:form prependId="false">
        <p:tabView id="primeFaces">
            <p:tab title="Primeiros exemplos">
                <h:panelGrid columns="2">
                    <h:outputLabel for="nome" value="Nome:"/>
                    <p:keyboard id="nome"/>
                    <h:outputLabel for="senha" value="Senha:"/>
                    <p:password id="senha" promptLabel="Digite a senha"
                                weakLabel="Senha fraca" strongLabel="Senha forte"
                                goodLabel="Senha razoável" feedback="true"/>
                    <h:outputLabel for="data" value="Data:"/>
                    <p:calendar id="data"
                                locale="#{geralBean.locale}"
                                pages="2"
                                showOn="button"
                                showOtherMonths="true"
                                selectOtherMonths="true"
                                value="#{primeFacesBean.data}"
                                showButtonPanel="true"
                    >
                        <p:ajax event="dateSelect" listener="#{primeFacesBean.definirData}"
                                update="mensagens"/>
                    </p:calendar>
                    <p:button value="Salvar (Ajax)"/>
                    <h:commandButton value="Salvar"/>
                </h:panelGrid>
            </p:tab>
            <p:tab title="Opinião">
                <h:outputText value="Gostou do Primefaces?"/>
                <p:rating stars="5"/>
            </p:tab>
            <p:tab title="Troca de tema">
                <!--
                <p:themeSwitcher initialText="Mude o tema" buttonPreText="Tema:" />
                -->
            </p:tab>
        </p:tabView>
        <!--</p:panel>-->
        <p:resizable for="primeFaces"/>
        <p:draggable for="primeFaces" opacity="0.6"/>
    </h:form>
</ui:composition>
</html>